### ISSUE TITLE
Cannot find BlockViewer.jar

### ISSUE THREAD

**Issue by ganesha1024** [thallium205/BitcoinVisualizer#14]
It is written that the following command will run the blockviewer: 

java -jar -Xmx2048m BlockViewer.jar -dbPath ../graph.db/ -configPath ../neo4j.properties -validate false -low -high -scraper -exporter

but there is no BlockViewer.jar that I can find in the project I downloaded (BitcoinVisualizer-master.zip) and there is no manifest in the project either, that I can find. I tried making the entire project into a jar, but without a manifest it was not executable.

**Comment by thallium205** [comment]
If you would like to build this from source, please use Eclipse.  Eclipse does not use manifest files, but instead uses .project files (which should be included).

**Comment by thallium205** [comment]
Also, I have updated the readme, please check out the detailed usage section.
